alias: "Alert if front door sensor battery too low"
trigger:
  - platform: numeric_state
    entity_id: sensor.front_door_batt
    below: 25
action:
  - service: notify.sms
    data:
      message: "Front door sensor has low battery!"
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "Front door sensor has low battery!"
      target:
        - !secret SMS_RACHAEL