alias: "Alert if master bedroom plant battery too low"
trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_plant_battery
    below: 15
condition:
  - condition: numeric_state
    entity_id: sensor.master_bedroom_plant_battery
    above: 0
action:
  - service: notify.sms
    data:
      message: "Master bedroom plant has low battery!"
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "Master bedroom plant has low battery!"
      target:
        - !secret SMS_RACHAEL