alias: "Toogle Pasta Part Reminder Off"
trigger:
  platform: event
  event_type: click
  event_data:
    entity_id: binary_sensor.switch_158d0002132898
    click_type: single
condition:
  - condition: state
    entity_id: input_boolean.alert_pasta_part
    state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.alert_pasta_part