alias: "Toogle Pasta Part Reminder On"
trigger:
  platform: event
  event_type: click
  event_data:
    entity_id: binary_sensor.switch_158d0002132898
    click_type: single
condition:
  - condition: state
    entity_id: input_boolean.alert_pasta_part
    state: 'off'
action:
  - service: timer.start
    entity_id: timer.pasta_part