homeassistant:
  name: Bulock Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
  customize: !include_dir_merge_named customizations

http:
  api_password: !secret password
  use_x_forwarded_for: True
  trusted_proxies: 10.0.0.50
  trusted_networks: 10.0.0.0/22
  ip_ban_enabled: True
  login_attempts_threshold: 10

sun:
system_health:
updater:
frontend:
  themes: !include_dir_named themes
  javascript_version: latest
zeroconf:
alexa:
config:
person:
lovelace:
  mode: yaml

history:
logbook:
recorder:
  db_url: !secret db_path
  purge_interval: 3
  purge_keep_days: 30
influxdb:
  host: nuc

binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list cameras
cast: !include cast.yaml
cloud: !include cloud.yaml
device_tracker: !include device_tracker.yaml
fan: !include_dir_merge_list fans
group: !include_dir_named groups
input_boolean: !include input_boolean.yaml
input_select: !include_dir_merge_named input_selects
intent_script: !include_dir_merge_named intent_scripts
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_players
plant: !include_dir_merge_named plants
scene: !include_dir_merge_list scenes
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches

ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key

cover:
  platform: opengarage
  covers:
      garage_door:
        host:  garagedoor
        device_key: !secret opengarage_key
        name:  Garage Door

customizer:
  custom_ui: local

ecobee:
  api_key: !secret ecobee_key

lutron_caseta_pro:
  bridges:
    - host: lutron
      fan: [ 17 ]

mqtt:
  discovery: true
  broker: mqtt
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

nest:
  client_id: !secret nest_client
  client_secret: !secret nest_secret
  binary_sensors:
    monitored_conditions:
      - 'person_detected'

octoprint:
  - host: kirk.3dprinter
    name: Select Mini
    api_key: !secret select_mini_octoprint_key
  - host: picard.3dprinter
    name: Mini Delta
    api_key: !secret mini_delta_octoprint_key

panel_iframe:
  nodered:
    title: Automation
    url: !secret node_red_url
    icon: mdi:cogs

speedtestdotnet:

vacuum:
  - platform: roomba
    host: roomba
    username: !secret roomba_user
    password: !secret roomba_pw

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key
      host: xiaomi




