alias: Set washing machine to running when power detected
trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    above: 10
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.washer
      state: Idle
    - condition: state
      entity_id: input_select.washer
      state: Clean
    - condition: state
      entity_id: input_select.washer
      state: Finishing
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.washer
      option: Running