alias: "Washing Machine Finished Cycle"
trigger:
 - platform: state
   entity_id: input_select.washer
   to: 'Clean'
action:
  - service: notify.sms
    data:
      message: "Clothes are washed for {{ states.input_select.washer_user.state }}."
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "Clothes are washed for {{ states.input_select.washer_user.state }}."
      target:
        - !secret SMS_RACHAEL
  - service: tts.google_say
    entity_id: media_player.downstairs_speaker
    data_template:
      message: "Clothes are washed for {{ states.input_select.washer_user.state }}."