alias: "Washing Machine Finished Cycle - Notify Hailey"
trigger:
 - platform: state
   entity_id: input_select.washer
   to: 'Clean'
condition:
  - condition: state
    entity_id: input_select.washer_user
    state: 'Hailey'
action:
  - service: notify.sms
    data:
      message: "Your clothes are done being washed."
      target:
        - !secret SMS_HAILEY
  - service: tts.google_say
    entity_id: media_player.haileys_bedroom_speaker
    data_template:
      message: "Your clothes are done being washed."