alias: Front door alert off
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_status
    to: 'off'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.alert_front_door