alias: Master Bedroom Plant alert off
trigger:
  - platform: numeric_state
    entity_id: sensor.master_bedroom_moisture
    above: 25
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.alert_master_bedroom_plant
