alias: "Keep Doors Locked Overnight"
trigger:
  - platform: state
    entity_id: lock.front_door_lock
    to: 'unlocked'
    for:
      minutes: 5
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: binary_sensor.front_door_status
      state: 'off'
action:
  - service: lock.lock
    entity_id: lock.front_door_lock