alias: "Turn on Kitchen Lighting at Night"
trigger:
  - platform: state
    entity_id: binary_sensor.breakfast_bar_sensor
    from: 'off'
    to: 'on'
condition:
  - condition: time
    after: '1:00:00'
    before: '8:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.kitchen_dim
