alias: "Turn on Kid's Bathroom Light Day"
trigger:
  - platform: state
    entity_id: binary_sensor.kids_bathroom_motion
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: light.kids_bathroom_lights
    state: 'off'
  - condition: time
    after: '8:00:00'
    before: '22:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.kids_bathroom_day