- platform: template
  sensors:
    stairs_motion_batt:
      value_template: '{{ states.zwave.stairs.attributes.battery_level }}'
      friendly_name: 'Downstairs Bathroom Motion'
      unit_of_measurement: '%'
    breakfast_bar_motion_batt:
      value_template: '{{ states.zwave.breakfast_bar.attributes.battery_level }}'
      friendly_name: 'Breakfast Bar Motion'
      unit_of_measurement: '%'
    basement_window_batt:
      value_template: '{{ states.zwave.basement_window.attributes.battery_level }}'
      friendly_name: 'Basement Window Sensor'
      unit_of_measurement: '%'
    front_door_batt:
      value_template: '{{ states.zwave.front_door_2.attributes.battery_level }}'
      friendly_name: 'Front Door Sensor'
      unit_of_measurement: '%'
    front_door_lock_batt:
      value_template: '{{ states.zwave.front_door_lock.attributes.battery_level }}'
      friendly_name: 'Front Door Lock'
      unit_of_measurement: '%'
    rear_door_batt:
      value_template: '{{ states.zwave.rear_door.attributes.battery_level }}'
      friendly_name: 'Rear Door Sensor'
      unit_of_measurement: '%'
    siren_batt:
      value_template: '{{ states.zwave.siren.attributes.battery_level }}'
      friendly_name: 'Siren'
      unit_of_measurement: '%'
    master_bathroom_sensor_batt:
      value_template: '{{ states.sensor.humidity_158d0001b952f4.attributes.battery_level }}'
      friendly_name: Master Bathroom Humidity Sensor
      unit_of_measurement: '%'
    kids_bathroom_sensor_batt:
      value_template: '{{ states.sensor.kids_bathroom_humidity.attributes.battery_level }}'
      friendly_name: Kid's Bathroom Humidity Sensor
      unit_of_measurement: '%'
    master_bathroom_motion_batt:
      value_template: '{{ states.binary_sensor.motion_sensor_158d0001e50edf.attributes.battery_level }}'
      friendly_name: Master Bathroom Motion Sensor
      unit_of_measurement: '%'
    kids_bathroom_motion_batt:
      value_template: '{{ states.binary_sensor.kids_bathroom_motion.attributes.battery_level }}'
      friendly_name: Kid's Bathroom Motion Sensor
      unit_of_measurement: '%'
    downstairs_bathroom_motion_batt:
      value_template: '{{ states.binary_sensor.downstairs_bathroom_motion.attributes.battery_level }}'
      friendly_name: Downstairs Bathroom Motion Sensor
      unit_of_measurement: '%'
    pasta_part_button_batt:
      value_template: '{{ states.binary_sensor.switch_158d0002132898.attributes.battery_level }}'
      friendly_name: Pasta Part Button
      unit_of_measurement: '%'
    laundry_motion_sensor_batt:
      value_template: '{{ states.binary_sensor.laundry_motion_sensor.attributes.battery_level }}'
      friendly_name: Laundry Motion Sensor
      unit_of_measurement: '%'

    washing_machine_status:
      value_template: '{{ states.input_select.washer.state }}'
      friendly_name: 'Status'
      icon_template: mdi:washing-machine

    # The difference in the bathroom humidity vs the humidity observed by the home humidistat
    master_bathroom_humidity_diff:
      value_template: '{{float(states.sensor.humidity_158d0001b952f4.state) - float(states.sensor.main_floor_humidity.state)}}'
      friendly_name: Master Bathroom Humidity Difference
      unit_of_measurement: '%'
    kids_bathroom_humidity_diff:
      value_template: '{{float(states.sensor.kids_bathroom_humidity.state) - float(states.sensor.main_floor_humidity.state)}}'
      friendly_name: Kid's Bathroom Humidity Difference
      unit_of_measurement: '%'

    # Take the current bathroom humidity difference and compare it to the average difference
    master_bathroom_humidity_diff_average_diff:
      value_template: '{{float(states.sensor.master_bathroom_humidity_diff.state) - float(states.sensor.master_bathroom_humidity_diff_average_mean.state)}}'
      friendly_name: Master Bathroom Humidity Difference Average Difference
    kids_bathroom_humidity_diff_average_diff:
      value_template: '{{float(states.sensor.kids_bathroom_humidity_diff.state) - float(states.sensor.kids_bathroom_humidity_diff_average_mean.state)}}'
      friendly_name: Kid's Bathroom Humidity Difference Average Difference

    vacuum_bin_full:
      value_template: '{{states.vacuum.roomba.attributes.bin_full}}'
      friendly_name: Vacuum Bin Full

    front_door_lock_action:
      friendly_name: 'Front Door Lock Action'
      value_template: >-
        {% if is_state('sensor.front_door_alarm_type', '18') %}
          {% if is_state('sensor.front_door_alarm_level', '0') %}
        Locked: Outside Keypad
          {% else %}
        Locked: User {{states('sensor.front_door_alarm_level')}}
          {% endif %}
        {% elif is_state('sensor.front_door_alarm_type', '19') %}
          Unlocked: User Code {{states('sensor.front_door_alarm_level')}}
        {% elif is_state('sensor.front_door_alarm_type', '21') %}
          Locked: {{[ 'Outside Lock', 'Inside Deadbolt', 'Outside Keypad' ][states('sensor.front_door_alarm_level')|int]}}
        {% elif is_state('sensor.front_door_alarm_type', '22') %}
          Unlocked: Inside Deadbolt
        {% else %}
          Unknown: {{states('sensor.front_door_alarm_type')}}/{{states('sensor.front_door_alarm_level')}}
        {% endif %}

