alias: Back door alert on
trigger:
  - platform: state
    entity_id: binary_sensor.back_door_status
    to: 'on'
    for:
      minutes: 2
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.alert_back_door
  - service: notify.sms
    data:
      message: "Back door has been left open."
      target:
        - !secret SMS_CAMERON
  - service: notify.sms
    data:
      message: "Back door has been left open."
      target:
        - !secret SMS_RACHAEL