alias: "Media player playing"
trigger:
  - platform: state
    entity_id: media_player.living_room, media_player.living_room_2, media_player.directv_receiver
    to: 'playing'
condition:
  - condition: time
    after: '21:00'
    before: '3:00'
action:
  - service: scene.turn_on
    entity_id: scene.downstairs_movie
