alias: "Turn off Master Bedroom TV When Not in Use"
trigger:
  - platform: state
    entity_id: media_player.master_bedroom
    from: 'playing'
    to: 'off'
    for:
      minutes: 8
action:
  - service: switch.turn_off
    entity_id: switch.master_bedroom_tv
