alias: "Door Unlock - Cameron"
trigger:
  - platform: state
    entity_id: sensor.front_door_lock_action
    to: 'Unlocked: User Code 1'
action:
  - service: tts.google_say
    entity_id: media_player.downstairs_speaker
    data_template:
      message: "Welcome home, Cameron."