alias: "Loft lights on at night"
trigger:
  - platform: time
    hours: 22
    minutes: 0
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
    - condition: state
      entity_id: group.kids
      state: 'home'
action:
    service: scene.turn_on
    entity_id: scene.loft_dim
