alias: Bathroom Plant alert off
trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_plant_moisture
    above: 20
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.alert_bathroom_plant